import antfu from '@antfu/eslint-config'
import { configs } from './src/index'

export default antfu(
  {
    rules: {
      'pnpm/yaml-enforce-settings': 'off',
      'jsonc/sort-keys': [
        'error',
        {
          order: [
            'publisher',
            'name',
            'displayName',
            'type',
            'version',
            'private',
            'packageManager',
            'description',
            'author',
            'contributors',
            'license',
            'funding',
            'homepage',
            'repository',
            'bugs',
            'keywords',
            'categories',
            'sideEffects',
            'imports',
            'exports',
            'main',
            'module',
            'unpkg',
            'jsdelivr',
            'types',
            'typesVersions',
            'bin',
            'icon',
            'files',
            'engines',
            'activationEvents',
            'contributes',
            'scripts',
            'peerDependencies',
            'peerDependenciesMeta',
            'dependencies',
            'optionalDependencies',
            'devDependencies',
            'pnpm',
            'overrides',
            'resolutions',
            'husky',
            'simple-git-hooks',
            'lint-staged',
            'eslintConfig',
          ],
          pathPattern: '^$',
        },
        // {
        //   order: { type: 'asc' },
        //   pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$',
        // },
        // {
        //   order: { type: 'asc' },
        //   pathPattern: '^(?:resolutions|overrides|pnpm.overrides)$',
        // },
        {
          order: { type: 'asc' },
          pathPattern: '^workspaces\\.catalog$',
        },
        {
          order: { type: 'asc' },
          pathPattern: '^workspaces\\.catalogs\\.[^.]+$',
        },
        {
          order: [
            'types',
            'import',
            'require',
            'default',
          ],
          pathPattern: '^exports.*$',
        },
        {
          order: [
            // client hooks only
            'pre-commit',
            'prepare-commit-msg',
            'commit-msg',
            'post-commit',
            'pre-rebase',
            'post-rewrite',
            'post-checkout',
            'post-merge',
            'pre-push',
            'pre-auto-gc',
          ],
          pathPattern: '^(?:gitHooks|husky|simple-git-hooks)$',
        },
      ],
    },
  },
  ...configs.recommended,
)
