packages: []
catalogs:
  build:
    tsdown: ^0.20.3
  dev:
    bumpp: ^10.4.1
    pncat: ^0.10.1
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  lint:
    '@antfu/eslint-config': ^7.4.3
    eslint: ^10.0.0
    lint-staged: ^16.2.7
  prod:
    jsonc-eslint-parser: ^2.4.2
  test:
    '@vitest/coverage-v8': 4.0.18
    eslint-vitest-rule-tester: ^3.1.0
    vitest: ^4.0.18
  types:
    '@types/node': ^24.10.13
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
